# **Taller 3**

## **Inteligencia Artificial**

### **Maestría en Analítica de Datos**

**Facultad de Ingeniería y Ciencias Básicas.**

**Universidad Central**

> **Integrantes:**

>>***1. Brayan Holman Paez Perez***

>>***2. Michel Esteven Céspedes Medina***


> **Profesor:**

>>***Hugo Franco***



## Librerias 
Librerias a utilizar

In [1]:
import numpy as np
from paquetes import *

## Funciones 
A continuacion para darle un mayor orden y entendimiento al taller, se dejaran las funciones  principales a utilizar en el mismo. 

## Puzzle Ejemplo

In [2]:
puzzle_array=np.array([[5,8,0],[2,1,4],[7,3,6]]) 
puzzleB=Puzzle8_State(None,0,puzzle_array)
print (puzzleB.getPosition())

[[5 8 0]
 [2 1 4]
 [7 3 6]]


## **2.Obtener la solución (secuencia de transiciones) del puzzle de 8 casillas mediante búsqueda noinformada:**

### A. Búsqueda «primero en profundidad» (DFS).


Celda de ejecucion para el metodo "primero en profundidad" usando el Puzzle ejemplo

In [3]:
primero_profundidad(puzzleB)

KeyboardInterrupt: 

### B. Búsqueda en profundidad limitada (DLS).

Celda de ejecucion para el metodo "Profundidad limitada" usando el Puzzle ejemplo. Donde el limite se define como menor estricto.

In [ ]:
profundidad_limitada(puzzleB,5)

### C. Búsqueda en profundidad iterada ID-DLS.

La funcion generada para encontrar la solucion por el metodo "Profundidad iterada" es la siguiente:

Celda de ejecucion para el metodo "Profundidad limitada iterada" usando el Puzzle ejemplo. 

In [ ]:
ID_DFS(puzzleB,18)

### D. Búsqueda en anchura (visto en la clase práctica, modificado para reportar la ruta -secuencia de transiciones- obtenida).

In [ ]:
primero_anchura(puzzleB)

## **3. Según el grafo especificado, implementar la búsqueda de costo uniforme para encontrar la ruta de menor coste entre Brest y:**

A continuacion definirimos el grafo con los estados propuestos y sus respectivos costos. Luego la funcion que calculara su costo de la ruta menos mediante el metodo de costo uniforme.

In [ ]:
grafo_estados= {
    'Brest':      (0,False),
    'Rennes':     (0,False),
    'Caen' :      (0,False),
    'Nantes':     (0,False),
    'Paris' :     (0,False),
    'Calais' :    (0,False),
    'Nancy' :     (0,False),
    'Strasbourg': (0,False),
    'Dijon':      (0,False),
    'Limoges':    (0,False),
    'Lyon':       (0,False),
    'Bordeaux':   (0,False),
    'Toulouse':   (0,False),
    'Montpellier':(0,False),
    'Avignon':    (0,False),
    'Grenoble':   (0,False),
    'Marseille':  (0,False),
    'Nice':       (0,False)}   
grafo_estructura = {
    "Calais" : [("Caen",120), ("Paris",297), ("Nancy",534)], 
    "Caen" : [("Calais",120), ("Paris",241), ("Rennes",176)], 
    "Rennes" : [("Caen",176), ("Nantes",107), ("Brest",244),("Paris",348)], 
    "Nantes" : [("Rennes",107), ("Limoges",329), ("Bordeaux",329)], 
    "Paris" : [("Calais",297), ("Caen",241), ("Rennes",348), ("Limoges",396), ("Dijon",313), ("Nancy",372)], 
    "Dijon" : [("Lyon",192), ("Strasbourg",335), ("Nancy",201),("Paris",313)], 
    "Nancy" : [("Dijon",201), ("Strasbourg",145), ("Calais",534),("Paris",372)], 
    "Strasbourg" : [("Dijon",335), ("Nancy",145)], 
    'Limoges'    : [('Nantes',329),('Paris',396),('Lyon',389),('Bordeaux', 220),('Toulouse', 313)],
    'Bordeaux'   : [('Nantes',329),('Limoges', 220),('Toulouse', 253)],
    'Toulouse'   : [('Bordeaux',253),('Limoges',313),('Montpellier', 240)],
    'Montpellier': [('Toulouse', 240), ('Avignon', 121)],
    'Lyon'       : [('Dijon', 192), ('Limoges', 389), ('Grenoble', 104), ('Avignon', 216)],
    'Grenoble'   : [('Lyon', 104), ('Avignon', 227)],
    'Avignon'    : [('Lyon', 216), ('Grenoble', 227), ('Montpellier', 121),('Marseille',99)],
    'Marseille'  : [('Avignon', 99), ('Nice', 188)],
    'Nice'       :  [('Marseille',188)],
    'Brest'       :  [('Rennes',244)]
}
grafo=StateGraph(grafo_estructura,grafo_estados)

## A. Grenoble

In [ ]:
result=UniformCostSearch(grafo, "Brest","Grenoble")

## B. Estrasburgo

In [ ]:
result=UniformCostSearch(grafo,"Brest", "Strasbourg")

## C. Marsella

In [ ]:
result=UniformCostSearch(grafo,"Brest", "Marseille")