# **Taller 4**

## **Inteligencia Artificial**

### **Maestría en Analítica de Datos**

**Facultad de Ingeniería y Ciencias Básicas.**

**Universidad Central**

> **Integrantes:**

>>***1. Brayan Holman Paez Perez***

>>***2. Michel Esteven Céspedes Medina***


> **Profesor:**

>>***Hugo Franco***



## Librerias 
Librerias a utilizar

In [1]:
import numpy as np
from paquetes_4 import *
import datetime 

# Taller : 

* Implementar una heurística consistente en la suma de las distancias de Manhattan (caminos por filas y columnas) de cada pieza del puzzle a su posición correcta en el estado solución:
<pre> 
[[1 2 3]
&nbsp;[4 5 6]
&nbsp;[7 8 0]]
&nbsp;
</pre>
* Implementar la solución al puzzle de 8 casillas mediante el método A* usando la heurística propuesta. 
* Comparar el desempeño de los métodos de búsqueda en anchura, profundidad iterada, primero-el-mejor y A* para resolver el puzzle de 8 casillas con la siguiente configuración (estado) inicial
<pre> 
[[5 8 0]
&nbsp;[2 1 4]
&nbsp;[7 3 6]]
</pre>

## Solución
### a. Implementar una heurística consistente en la suma de las distancias de Manhattan (caminos por filas y columnas) de cada pieza del puzzle a su posición correcta en el estado solución:

Estado inicial a utilizar del puzzle para los metodos dados


In [1]:
puzzle_array=np.array([[5,8,0],[2,1,4],[7,3,6]])
puzzleB=Puzzle8_State(None,0,puzzle_array)
print (puzzleB.getPosition())

NameError: name 'np' is not defined

"Primero el mejor"-Heurística Manhatan

In [3]:
%%time
t_inicial = datetime.datetime.now()
puzzle_man=Puzzle8_State(None,0,puzzleB.getPosition())
puzzle_man.heuristic_val=heuristic_manh(puzzle_man)
solution_man=Puzzle8_bestfirst_inf(puzzle_man)
t_final = datetime.datetime.now() 
t_first_manh = t_final-t_inicial
t_first_manh=float(str(t_first_manh.seconds)+'.'+str(t_first_manh.microseconds))
print('Tiempo transcurrido %s Segundos '%(t_first_manh))

[[0 3 5]
 [1 7 2]
 [8 4 6]]
Visité el estado 0, pero no es solución
[[0 3 5]
 [1 7 2]
 [8 4 6]]
[[1 3 5]
 [0 7 2]
 [8 4 6]]
Visité el estado 1, pero no es solución
[[1 3 5]
 [0 7 2]
 [8 4 6]]
[[1 3 5]
 [8 7 2]
 [0 4 6]]
Visité el estado 3, pero no es solución
[[1 3 5]
 [8 7 2]
 [0 4 6]]
[[1 3 5]
 [7 0 2]
 [8 4 6]]
Visité el estado 4, pero no es solución
[[1 3 5]
 [7 0 2]
 [8 4 6]]
[[1 3 5]
 [8 7 2]
 [4 0 6]]
Visité el estado 5, pero no es solución
[[1 3 5]
 [8 7 2]
 [4 0 6]]
[[1 3 5]
 [8 7 2]
 [4 6 0]]
Visité el estado 10, pero no es solución
[[1 3 5]
 [8 7 2]
 [4 6 0]]
[[1 0 5]
 [7 3 2]
 [8 4 6]]
Visité el estado 6, pero no es solución
[[1 0 5]
 [7 3 2]
 [8 4 6]]
[[1 3 5]
 [7 2 0]
 [8 4 6]]
Visité el estado 8, pero no es solución
[[1 3 5]
 [7 2 0]
 [8 4 6]]
[[1 3 5]
 [7 2 6]
 [8 4 0]]
Visité el estado 15, pero no es solución
[[1 3 5]
 [7 2 6]
 [8 4 0]]
[[1 3 5]
 [7 2 6]
 [8 0 4]]
Visité el estado 16, pero no es solución
[[1 3 5]
 [7 2 6]
 [8 0 4]]
[[1 3 5]
 [7 2 6]
 [0 8 4]]
Visité el

 [7 8 4]]
Visité el estado 190, pero no es solución
[[5 1 3]
 [2 0 6]
 [7 8 4]]
[[0 2 3]
 [1 5 4]
 [7 6 8]]
Visité el estado 194, pero no es solución
[[0 2 3]
 [1 5 4]
 [7 6 8]]
[[1 2 3]
 [7 5 4]
 [0 6 8]]
Visité el estado 195, pero no es solución
[[1 2 3]
 [7 5 4]
 [0 6 8]]
[[1 2 3]
 [7 5 0]
 [4 6 8]]
Visité el estado 198, pero no es solución
[[1 2 3]
 [7 5 0]
 [4 6 8]]
[[5 1 3]
 [0 2 6]
 [7 8 4]]
Visité el estado 199, pero no es solución
[[5 1 3]
 [0 2 6]
 [7 8 4]]
[[1 2 3]
 [7 5 4]
 [6 0 8]]
Visité el estado 203, pero no es solución
[[1 2 3]
 [7 5 4]
 [6 0 8]]
[[1 2 3]
 [7 5 4]
 [6 8 0]]
Visité el estado 208, pero no es solución
[[1 2 3]
 [7 5 4]
 [6 8 0]]
[[1 2 3]
 [7 5 0]
 [6 8 4]]
Visité el estado 209, pero no es solución
[[1 2 3]
 [7 5 0]
 [6 8 4]]
[[1 2 3]
 [8 7 6]
 [0 5 4]]
Visité el estado 184, pero no es solución
[[1 2 3]
 [8 7 6]
 [0 5 4]]
[[1 2 3]
 [5 0 4]
 [7 6 8]]
Visité el estado 164, pero no es solución
[[1 2 3]
 [5 0 4]
 [7 6 8]]
[[1 2 0]
 [7 5 3]
 [6 8 4]]
Visité el 

### b. Implementar la solución al puzzle de 8 casillas mediante el método A* usando la heurística propuesta.

In [4]:
%%time
t_inicial = datetime.datetime.now()
puzzle_AA_=Puzzle8_State(None,0,puzzleB.getPosition())
puzzle_AA_.heuristic_val=heuristic_manh(puzzle_AA_)
solution_aa=Puzzle8_AA_(puzzle_AA_)
t_final = datetime.datetime.now() 
t_aa = t_final-t_inicial
t_aa=float(str(t_aa.seconds)+'.'+str(t_aa.microseconds))
print('Tiempo transcurrido %s Segundos '%(t_aa))

[[0 3 5]
 [1 7 2]
 [8 4 6]]
Visité el estado 0, pero no es solución
[[0 3 5]
 [1 7 2]
 [8 4 6]]
[[1 3 5]
 [0 7 2]
 [8 4 6]]
Visité el estado 1, pero no es solución
[[1 3 5]
 [0 7 2]
 [8 4 6]]
[[1 3 5]
 [8 7 2]
 [0 4 6]]
Visité el estado 3, pero no es solución
[[1 3 5]
 [8 7 2]
 [0 4 6]]
[[1 3 5]
 [7 0 2]
 [8 4 6]]
Visité el estado 4, pero no es solución
[[1 3 5]
 [7 0 2]
 [8 4 6]]
[[3 0 5]
 [1 7 2]
 [8 4 6]]
Visité el estado 2, pero no es solución
[[3 0 5]
 [1 7 2]
 [8 4 6]]
[[1 0 5]
 [7 3 2]
 [8 4 6]]
Visité el estado 6, pero no es solución
[[1 0 5]
 [7 3 2]
 [8 4 6]]
[[1 3 5]
 [7 2 0]
 [8 4 6]]
Visité el estado 8, pero no es solución
[[1 3 5]
 [7 2 0]
 [8 4 6]]
[[1 3 5]
 [7 2 6]
 [8 4 0]]
Visité el estado 14, pero no es solución
[[1 3 5]
 [7 2 6]
 [8 4 0]]
[[1 3 5]
 [8 7 2]
 [4 0 6]]
Visité el estado 5, pero no es solución
[[1 3 5]
 [8 7 2]
 [4 0 6]]
[[1 3 5]
 [8 7 2]
 [4 6 0]]
Visité el estado 17, pero no es solución
[[1 3 5]
 [8 7 2]
 [4 6 0]]
[[1 3 5]
 [7 4 2]
 [8 0 6]]
Visité el 

### c. Comparar el desempeño de los métodos de búsqueda en anchura, profundidad iterada, primero-el-mejor y A* para resolver el puzzle de 8 casillas con la siguiente configuración (estado) inicial
<pre> 
[[5 8 0]
&nbsp;[2 1 4]
&nbsp;[7 3 6]]
</pre>

In [5]:
%%time
t_inicial = datetime.datetime.now()
solution_iterada,level_iterada=ID_DFS(puzzleB,18)
t_final = datetime.datetime.now() 
t_iterada= t_final-t_inicial
t_iterada=float(str(t_iterada.seconds)+'.'+str(t_iterada.microseconds))
print('Tiempo transcurrido %s Segundos '%(t_iterada))

El resultado para esta iteración  0  es : seguir
El resultado para esta iteración  1  es : seguir
El resultado para esta iteración  2  es : seguir
El resultado para esta iteración  3  es : seguir
El resultado para esta iteración  4  es : seguir
El resultado para esta iteración  5  es : seguir
El resultado para esta iteración  6  es : seguir
El resultado para esta iteración  7  es : seguir
El resultado para esta iteración  8  es : seguir
El resultado para esta iteración  9  es : seguir
El resultado para esta iteración  10  es : seguir
El resultado para esta iteración  11  es : seguir

El estado solución es: 67679
[[1 2 3]
 [4 5 6]
 [7 8 0]]
El resultado para esta iteración  12  es : success
Tiempo transcurrido 7.394508 Segundos 
Wall time: 7.4 s


In [6]:
t_inicial = datetime.datetime.now()
solution_anchura=primero_anchura(puzzleB)
t_final = datetime.datetime.now() 
t_anchura= t_final-t_inicial
t_anchura=float(str(t_anchura.seconds)+'.'+str(t_anchura.microseconds))
print('Tiempo transcurrido %s Segundos '%(t_anchura))


 Metodo: Busqueda en Anchura 
 Pasos a seguir para hallar la solución 
 
[[0 3 5]
 [1 7 2]
 [8 4 6]] 0 	 paso: 0 

[[1 3 5]
 [0 7 2]
 [8 4 6]] 1 	 paso: 1 

[[1 3 5]
 [7 0 2]
 [8 4 6]] 4 	 paso: 2 

[[1 3 5]
 [7 4 2]
 [8 0 6]] 9 	 paso: 3 

[[1 3 5]
 [7 4 2]
 [0 8 6]] 19 	 paso: 4 

[[1 3 5]
 [0 4 2]
 [7 8 6]] 37 	 paso: 5 

[[1 3 5]
 [4 0 2]
 [7 8 6]] 64 	 paso: 6 

[[1 3 5]
 [4 2 0]
 [7 8 6]] 109 	 paso: 7 

[[1 3 0]
 [4 2 5]
 [7 8 6]] 189 	 paso: 8 

[[1 0 3]
 [4 2 5]
 [7 8 6]] 320 	 paso: 9 

[[1 2 3]
 [4 0 5]
 [7 8 6]] 519 	 paso: 10 

[[1 2 3]
 [4 5 0]
 [7 8 6]] 839 	 paso: 11 

[[1 2 3]
 [4 5 6]
 [7 8 0]] 1353 	 paso: 12 

Tiempo transcurrido 20.13766 Segundos 


>> # Comparación de Desempeños

In [7]:
from tabulate import tabulate

table = [["Anchura",solution_anchura.level,t_anchura,solution_anchura.label],
         ["Profundidad iterada",level_iterada,t_iterada,None],
         ["Primero el mejor (Manh)",solution_man.level,t_first_manh,solution_man.label],
         ["A*",solution_aa.level,t_aa,solution_aa.label]]
print(tabulate(table,headers=['Metodo','Profundidad','Tiempo','Etiqueta']))

Metodo                     Profundidad     Tiempo    Etiqueta
-----------------------  -------------  ---------  ----------
Anchura                             12  20.1377          1353
Profundidad iterada                 12   7.39451
Primero el mejor (Manh)             58   0.352061         313
A*                                  12   0.26928           80
